server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: debug

weather:
  api:
    key: 73f1ce8328522e4eb97aab95d79cf90d
    url: https://api.openweathermap.org/data/2.5